# Generated by Django 4.2.3 on 2024-07-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyabron',
            name='tel_raqam',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='polyabron',
            name='tel_raqam2',
            field=models.CharField(max_length=13),
        ),
    ]
