# Generated by Django 4.2.3 on 2024-07-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_polyabron_tel_raqam_alter_polyabron_tel_raqam2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyabron',
            name='vaqti',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='polyabron',
            unique_together={('kun', 'vaqti')},
        ),
        migrations.DeleteModel(
            name='Vaqt',
        ),
    ]
