# Generated by Django 4.2.3 on 2024-07-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_polyabron_vaqti_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqti', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='polyabron',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='polyabron',
            name='ismfamilya',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polyabron',
            name='izoh',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='polyabron',
            name='jamo1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polyabron',
            name='jamo2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polyabron',
            name='tel_raqam',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='polyabron',
            name='tel_raqam2',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='polyabron',
            name='vaqti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.time'),
        ),
    ]
